/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:d3b5d5cbe6ed35d120b14ef7e15feef9:1f57b0fb238d92eed8a8aa4f80d62478:89f2fac29211a8ba8cd8af62d60d99d6$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class TheWise
	{
		public const string NPCTheWise001 = "NPCTheWise001";
		public const string NPCTheWise002 = "NPCTheWise002";
		public const string NPCTheWise003 = "NPCTheWise003";
		public const string NPCTheWise004 = "NPCTheWise004";
		public const string NPCTheWise005 = "NPCTheWise005";
		public const string NPCTheWise006 = "NPCTheWise006";
	}
}